### ISSUE TITLE
Troubles with Multiple Displays

### ISSUE THREAD

**Issue by hudson-ayers** [alex-spataru/HiDPI-Fixer#3] opened 2018-09-19 18:08 UTC
When attempting to connect a second monitor to my laptop, I find that my display settings get very weird again. I have attempted to correct this by rerunning the HiDPI fixer for each screen -- unfortunately, when I attempt to rescale the second display I get the error "QStringList MainWindow::availableResolutions(int) xrandr returned exit code 1"

**Comment by alex-spataru** [comment] 2018-09-20 00:32
Thanks for your report!

The issue lies in the implementation of [`XrandrGetAvailableResolutions(const int)`](https://github.com/alex-spataru/HiDPI-Fixer/blob/master/src/XRandrBridge.cpp#L98) function. Unfortunately, I do not have any secondary monitor to test any changes in the function (and don't know what the `xrandr` output would look like if you had more than one monitor attached.

If possible, could you please post the output of the following terminal commands:
- `xrandr ----listactivemonitors`
- `xrandr --screen`

With that information, I can begin to re-implement the Xrandr-related functions of this application.

Thanks!

**Comment by hudson-ayers** [comment] 2018-09-20 00:36
```
hudson: ~ $ xrandr --listactivemonitors
Monitors: 2
 0: +*eDP-1 2560/345x1440/194+0+0  eDP-1
 1: +DP-2 4480/550x1440/340+0+0  DP-2
```

```
hudson: ~ $ xrandr --screen
xrandr: --screen requires an argument
Try 'xrandr --help' for more information.
```

```
hudson: ~ $ xrandr --screen 0
Screen 0: minimum 320 x 200, current 4480 x 1440, maximum 8192 x 8192
eDP-1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 345mm x 194mm
   3840x2160     60.00 +  59.98    59.97    40.00  
   3200x1800     59.96    59.94  
   2880x1620     59.96    59.97  
   2560x1600     59.99    59.97  
   2560x1440     59.99    59.99*   59.96    59.95  
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 4480x1440+0+0 (normal left inverted right x axis y axis) 550mm x 340mm panning 4480x1440+0+0
   1920x1200     59.95*+
   1920x1080     60.00    50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1440x576i     50.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
```
```
hudson: ~ $ xrandr --screen 1
Invalid screen number 1 (display has 1)
```

**Comment by hudson-ayers** [comment] 2018-09-20 00:38
I think the issue is that you are calling `xrandr --screen 1`, when instead you should be parsing the resolution for the second monitor for the output from `xrandr --screen 0` somehow. But I did not look into your code very thoroughly so I could be wrong.

By the way, thank you for making this tool!

**Comment by alex-spataru** [comment] 2018-09-20 00:42
Thanks for the outputs! Indeed, the issue is that `xrandr --screen 1` does not return any resolution at all. I'll begin working on a fix and keep you updated.

**Comment by philliptee** [comment] 2018-11-02 20:52
I'm interested to see this work too.

**Comment by alex-spataru** [comment] 2018-12-18 19:32
Sorry for the late reply, I was busy with exams and college stuff. I have made several changes to the project, which include detecting the individual resolutions for each display.

You can download the latest release at: https://github.com/alex-spataru/HiDPI-Fixer/releases/tag/v1.3

Please let me know if the new release works for your respective configurations!

**Comment by alex-spataru** [comment] 2018-12-19 01:29
#### Update

Please download the AppImage from this link: https://github.com/alex-spataru/HiDPI-Fixer/releases/tag/continuous
This version is built using Travis and should fix some compatibility issues with older distros.

**Comment by alex-spataru** [comment] 2019-02-03 02:25
Closing issue, if you still have problems, feel free to open this issue again!

**Closed as completed by alex-spataru** 2019-02-03 02:25 UTC
